language: java

sudo: false

jdk: oraclejdk8

script: 
- mvn test
- mvn package
- mvn cobertura:cobertura

branches:
  only:
  - master
  - development

after_success:
- bash <(curl -s https://codecov.io/bash)
